name: 'Build flutter-tizen tpk'
description: 'Build flutter-tizen tpk'
inputs:
  project-root:
    description: 'The root of your flutter-tizen project'
    required: false
    default: $GITHUB_WORKSPACE
  tizen-studio-version:
    description: 'Tizen Studio version (default 4.1)'
    required: false
    default: '4.1'
  certificate-file:
    description: 'Signing certificate file'
    required: true
  certificate-password:
    description: 'Signing certificate password'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt update
        sudo apt install python3 curl file git make xz-utils zip
        mkdir /usr/bin/env
        ln -s /usr/bin/python3 /usr/bin/env/python3
      shell: bash

    - run: |
        curl http://download.tizen.org/sdk/Installer/tizen-studio_${{ inputs.tizen-studio-version }}/web-cli_Tizen_Studio_${{ inputs.tizen-studio-version }}_ubuntu-64.bin > tizen-studio.bin
        chmod 755 tizen-studio.bin
        mkdir tizen-studio
        ./tizen-studio.bin --no-java-check --accept-license $GITHUB_WORKSPACE/tizen-studio
        rm tizen-studio.bin
      shell: bash

    - run: |
        export PATH=$GITHUB_WORKSPACE/tizen-studio/tools:$GITHUB_WORKSPACE/tizen-studio/tools/ide/bin:$PATH
        tizen security-profiles add -n ActionsProfile -a ${{ inputs.certificate-file }} -p "${{ inputs.certificate-password }}"
        tizen cli-config "profiles.path=$GITHUB_WORKSPACE/tizen-studio-data/profile/profiles.xml"
      shell: bash

    - run: |
        mkdir flutter-tizen
        git clone https://github.com/flutter-tizen/flutter-tizen.git flutter-tizen
      shell: bash

    - run: |
        export PATH=$GITHUB_WORKSPACE/tizen-studio/tools:$GITHUB_WORKSPACE/tizen-studio/tools/ide/bin:$PATH
        export PATH=$GITHUB_WORKSPACE/flutter-tizen/bin
        flutter-tizen build tpk
      shell: bash
