name: 'Build flutter-tizen tpk'
description: 'Build flutter-tizen tpk'
inputs:
  project-root:
    description: 'The root of your flutter-tizen project'
    required: false
    default: $GITHUB_WORKSPACE
  tizen-studio-version:
    description: 'Tizen Studio version (default 4.1)'
    required: false
    default: '4.1'
  tizen-platform:
    description: 'The api level your app'
    required: false
    default: 'WEARABLE-5.5'
  author-certificate-file:
    description: 'Author certificate file'
    required: true
  author-certificate-password:
    description: 'Author certificate password'
    required: true
  distributor-certificate-file:
    description: 'Distributor certificate file'
    required: true
  distributor-certificate-password:
    description: 'Distributor certificate password'
    required: false
    default: 'tizenpkcs12passfordsigner'

runs:
  using: "composite"
  steps:
    - run: |
        sudo apt update
        sudo apt install libpython2.7 expect gettext
      shell: bash

    - run: |
        curl http://download.tizen.org/sdk/Installer/tizen-studio_${{ inputs.tizen-studio-version }}/web-cli_Tizen_Studio_${{ inputs.tizen-studio-version }}_ubuntu-64.bin > tizen-studio.bin
        chmod 755 tizen-studio.bin
        mkdir tizen-studio
        ./tizen-studio.bin --no-java-check --accept-license $GITHUB_WORKSPACE/tizen-studio
        rm tizen-studio.bin
      shell: bash

    - run: |
        export PATH=$GITHUB_WORKSPACE/tizen-studio/tools:$GITHUB_WORKSPACE/tizen-studio/tools/ide/bin:$PATH
        tizen security-profiles add -A -n ActionsProfile -a ${{ inputs.author-certificate-file }} -p "${{ inputs.author-certificate-password }}" -d ${{ inputs.distributor-certificate-file }} -dp "${{ secrets.distributor-certificate-password }}"
        tizen cli-config "profiles.path=$GITHUB_WORKSPACE/tizen-studio-data/profile/profiles.xml"
      shell: bash

    - run: |
        mkdir flutter-tizen
        git clone https://github.com/flutter-tizen/flutter-tizen.git flutter-tizen
      shell: bash

    - run: |
        export PATH=$GITHUB_WORKSPACE/tizen-studio/tools:$GITHUB_WORKSPACE/tizen-studio/tools/ide/bin:$PATH
        export PATH=$GITHUB_WORKSPACE/tizen-studio/package-manager:$PATH
        export PATH=$GITHUB_WORKSPACE/flutter-tizen/bin:$PATH
        package-manager-cli.bin install --accept-license NativeCLI NativeToolchain-Gcc-9.2 Certificate-Manager cert-add-on ${{ inputs.tizen-platform }}-NativeAppDevelopment-CLI
        flutter-tizen pub get
        flutter-tizen build tpk
        tizen cli-config -l
        cat tizen-studio-data/profile/profiles.xml
      shell: bash
